### ISSUE TITLE
/storageroom, PUT: /:id

### ISSUE THREAD

**Issue by Lojdquist** [C4SolutionsTDDC88/back-end#14] opened 2019-10-04 07:13 UTC
Requirements: FR55

request: PUT
endpoint: /storageroom/:id

Updates the specified storage room object { “name”: room_name, "branch": branch_id}

**Comment by gustavaa** [comment] 2019-10-15 18:18
Duplicate of #9, closing issue

**Closed as completed by gustavaa** 2019-10-15 18:18 UTC
Labels: duplicate, Feature, Low
